# NOTE:           update this with your service name
service: hackOne-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

environment:
  MONGO_USER: ${env:MONGO_USER}
  MONGO_PASSWORD: ${env:MONGO_PASSWORD}
  AWS_ACCESS_KEY_ID: ${env:AWS_ACC_KEY_ID}
  AWS_SECRET: ${env:AWS_SECRET}
  AWS_USER_POOL_ID: ${env:AWS_USER_POOL_ID}
  ACCESS_CONTROL_ALLOW_ORIGIN: ${env:ACCESS_CONTROL_ALLOW_ORIGIN}

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    port: 3001
  dotenv:
    path: .env.production

functions:
  edithack:
    handler: editHack.edit
    events:
      - http:
          path: edithack
          method: post
          cors: true
  authuser:
    handler: authUser.auth
    events:
      - http:
          path: auth
          method: post
          cors: true
  registeruser:
    handler: registerUser.register
    events:
      - http:
          path: register
          method: post
          cors: true
  hackdetail:
    handler: hackDetail.detail
    events:
      - http:
          path: hackdetail/{id}
          method: get
          cors: true
  addhack:
    handler: addHack.add
    events:
      - http:
          path: addhack
          method: post
          cors: true
  joinhack:
    handler: joinHack.join
    events:
      - http:
          path: joinhack
          method: post
          cors: true
  gethacklist:
    handler: getHacks.list
    events:
      - http:
          path: hacklist
          method: get
          cors: true
